### PR TITLE
Add Workspace Id to publisher proto

### PR DESCRIPTION
**Pull request by seswarrajan**
Signed-off-by: Eswar Rajan Subramanian <eswar@accuknox.com>

### CODE REVIEW

**Comment by Ankurk99** [comment]
What is this workspace_id and how will it be useful for us?

**Comment by seswarrajan** [comment]
> What is this workspace_id and how will it be useful for us?

While onboarding a worker cluster, each worker cluster is given an unique workspace ID. This workspace Id will help in identifying that worker cluster. This will be more helpful in SaaS .

**Review by rajaSahil — APPROVED** [review]
LGTM

**Comment by wazir-ahmed** [comment]
@seswarrajan How DE knows the `workspace_id` for the cluster in which it is running? Are we using config params or env vars?

**Comment by seswarrajan** [comment]
We set it as env variable while onboarding the cluster. 

image

**Comment by wazir-ahmed** [comment]
> We set it as env variable while onboarding the cluster.

Okay, we already added the support for it, :rocket:

**Comment by seswarrajan** [comment]
> > We set it as env variable while onboarding the cluster.
> 
> Okay, we already added the support for it, rocket

From feeder-service ?

**Review by wazir-ahmed — APPROVED** [review]

**Comment by wazir-ahmed** [comment]
> From feeder-service ?

My question is, if I add the workspace, cluster_name env to DE today, will it work?

**Comment by seswarrajan** [comment]
> > From feeder-service ?
> 
> My question is, if I add the workspace, cluster_name env to DE today, will it work?

With this PR, if we add workpsaceId and cluster_name to the env, it will work.

**Pull request merged**
