### PR TITLE
feat: bump go version to 1.20 and bump dependency versions

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Signed-off-by: Vyom-Yadav [jackhammervyom@gmail.com](mailto:jackhammervyom@gmail.com)

---

- Bumped go version for `src` and `test` to 1.20.
- Bumped go version in CI Actions.
- Bumped dependency versions.
- Bumped `test` dependency versions.
Resolved conflicts, and ambiguous imports.

### CODE REVIEW

**Review by seswarrajan — APPROVED** [review]
LGTM.. Is this tested with creating a container image ?

**Comment by Vyom-Yadav** [comment]
I suspect something broke. The CI failure does not look like it is the regular flake we are encountering.

Regular failure: https://github.com/accuknox/discovery-engine/actions/runs/4635840191/jobs/8203209391?pr=705

This PR: https://github.com/accuknox/discovery-engine/actions/runs/4786944680/jobs/8511519498?pr=714

Edit:

Reverted cilium to the previous version, works fine now.

**Comment by Vyom-Yadav** [comment]
> Is this tested with creating a container image ?

```Dockerfile
FROM artifactory.accuknox.com/accuknox/golang:1.18.0-bullseye as builder
```
We would need `go` version `1.20`, not sure if that exists.

**Comment by Vyom-Yadav** [comment]
@seswarrajan https://github.com/accuknox/discovery-engine/pull/714#issuecomment-1520240061 still needs to be done. (Not sure if in the scope of this PR)

Apart from that, I tried building the image locally, and it worked. CI failure is known flake.

**Comment by daemon1024** [comment]
> Apart from that, I tried building the image locally, and it worked. CI failure is known flake.

Just wanted confirm whether the built image was deployed and tested in some k8s env? Changes LGTM

**Review by nyrahul — APPROVED** [review]
LGTM

**Comment by nyrahul** [comment]
@Vyom-Yadav , was there any specific reason to bump these versions ? Especially the go ver to 1.20?

**Comment by Vyom-Yadav** [comment]
> was there any specific reason to bump these versions ?

Yes, I wanted to update the Kyverno dependency, but updating it alone wasn't sufficient as other dependencies required a lower versions of both direct and indirect dependencies. So other dependencies also had to be updated.

Kyverno was getting downgraded if only it was updated (with `-u`).

> Especially the go ver to 1.20?

```
go.uber.org/multierr@v1.11.0/error.go:209:20: undefined: atomic.Bool
note: module requires Go 1.20
```

The error was similar to this, some dependencies required and updated version of Go.

**Comment by Vyom-Yadav** [comment]
> Just wanted confirm whether the built image was deployed and tested in some k8s env? 

Yes, I tested DE in a local cluster.

**Pull request merged**
