### PR TITLE
Update stable version to 0.9.1

### PR DESCRIPTION
**Pull request by seswarrajan**
**Purpose of PR?**: 
To update the stable version of DE to 0.9.1

Fixes #
NA

**Does this PR introduce a breaking change?**
NO

**If the changes in this PR are manually verified, list down the scenarios covered:**:
NO

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by seswarrajan** [comment]
Do not merge this PR, until the helm charts for DE is updated. This contains changes in configmap values as well.

**Comment by Ankurk99** [comment]
@seswarrajan Have we tested discovery-engine across different platforms before marking it stable? Can you please write down the env. where it's tested?

**Comment by seswarrajan** [comment]
> @seswarrajan Have we tested discovery-engine across different platforms before marking it stable? Can you please write down the env. where it's tested?

@Ankurk99 I have tested it in aks cluster for deployments, replicasets and stateful sets.

Tested 
1. AD policies.
2. Recommendation policies. 

Also testing is still in progress.

**Comment by seswarrajan** [comment]
Temporarily closing it

**Pull request closed without merging**
