### PR TITLE
cilium: refactored code related fromEntities

### PR DESCRIPTION
**Pull request by wazir-ahmed**
* Refactored existing code
* Fixed some issues in policies based on `fromEntities` rule

Signed-off-by: Wazir Ahmed <wazir@accuknox.com>

### CODE REVIEW

**Comment by wazir-ahmed** [comment]
This should have been part of #439. Missed to push this commit before the PR is merged.

**Review by nyrahul — DISMISSED** [review]

**Comment by nyrahul** [comment]
@wazir-ahmed , can you please fix the unit-tests failing.

**Comment by wazir-ahmed** [comment]
@nyrahul Ok. I will fix the failing test-cases.

**Comment by wazir-ahmed** [comment]
@nyrahul Unit-tests are fixed now.

**Pull request merged**
