### PR TITLE
Fix for Systemd mode of knoxAutoPolicy is not working

### PR DESCRIPTION
**Pull request by seswarrajan**
Signed-off-by: Eswar Rajan Subramanian [eswar@accuknox.com](mailto:eswar@accuknox.com)

### CODE REVIEW

**Comment by Prateeknandle** [comment]
@seswarrajan can you fix the go-sec errors

**Comment by nyrahul** [comment]
Folks, please fix the go-sec errors.
@Prateeknandle , please fix the ginkgo test problems as well in a separate PR.

**Comment by seswarrajan** [comment]
Gosec errors are fixed. Kindly approve

**Comment by Ankurk99** [comment]
@seswarrajan PR looks fine. Can you please fix the lint error and squash the commits?

**Comment by seswarrajan** [comment]
All errors resolved. Kindly review and comment on the same.

**Review by nyrahul — APPROVED** [review]

**Pull request merged**
