### PR TITLE
improving tests

### LINKED ISSUE #682: [Bug] ginkgo tests are flaky
issues with the tests :
1. Sometimes Network Policies are not generated as per expectations. For ex - [https://github.com/accuknox/discovery-engine/actions/runs/4371921390/jobs/7648698715#step:7:2100](https://github.com/accuknox/discovery-engine/actions/runs/4371921390/jobs/7648698715#step:7:2100) here network policies should have `port: 3306` & `protocol: TCP` for both the pods(wordpress as well as mysql). Right Now we iterate for 30 times to get an ideal policy, but we are still not getting them(sometimes).

### PR DESCRIPTION
**Pull request by Prateeknandle**
fixes #682 

changes:
- capturing errors
- removing `bind points` case for mysql pod summary

### CODE REVIEW

**Comment by Prateeknandle** [comment]
FYI: Tests are working fine now. For summary it is still getting failed because summary data is unordered, when we get the new release it'll be fixed. I'll check tests once more when we get new release and then we can merge this pr.

**Comment by Ankurk99** [comment]
> because summary data is unordered, when we get the new release it'll be fixed. I'll check tests once more when we get new release and then we can merge this pr.

How will this be fixed with the new release? Do we have any PR for that?

**Comment by Prateeknandle** [comment]
> How will this be fixed with the new release? Do we have any PR for that?

Fixed by #737

**Comment by Prateeknandle** [comment]
handled by https://github.com/accuknox/discovery-engine/pull/769

**Pull request closed without merging**
