### PR TITLE
Update discovery-engine to send workspace_id and cluster_id with policies

### PR DESCRIPTION
**Pull request by stefin9898**
Changed the `protobuf` files to send `workspace_id` and `cluster_id` with policies

### CODE REVIEW

**Comment by wazir-ahmed** [comment]
@seswarrajan @stefin9898 Both this PR and PR #630 are trying to add `cluster_id` in `PolicyYaml` structure. Maybe commits from either one of the PR can be moved to other PR. @stefin9898 and @seswarrajan Please discuss on how we can proceed here.

**Review by seswarrajan — APPROVED** [review]
LGTM.

**Review by wazir-ahmed — APPROVED** [review]
PR looks good to me. Thanks @stefin9898.

**Comment by wazir-ahmed** [comment]
@stefin9898 Please squash the commits and update the commit description.

**Review by seswarrajan — APPROVED** [review]
LGTM

**Pull request merged**
