### PR TITLE
Change to deploy discovery-engine in accuknox-agents namespace

### PR DESCRIPTION
**Pull request by seswarrajan**
Signed-off-by: Eswar Rajan Subramanian <eswar@accuknox.com>

### CODE REVIEW

**Review by achrefbensaad — APPROVED** [review]
LGTM!

**Review by rajaSahil — APPROVED** [review]

**Comment by Ankurk99** [comment]
Hey @seswarrajan, if we try to install using the README manifest will it be directly deployed in the accuknox-agent ns or would we have to pass the `-n accuknox-agent` flag?
edit: Talking about this `kubectl apply -f https://raw.githubusercontent.com/accuknox/discovery-engine/dev/deployments/k8s/deployment.yaml`

**Comment by seswarrajan** [comment]
> Hey @seswarrajan, if we try to install using the README manifest will it be directly deployed in the accuknox-agent ns or would we have to pass the `-n accuknox-agent` flag? edit: Talking about this `kubectl apply -f https://raw.githubusercontent.com/accuknox/discovery-engine/dev/deployments/k8s/deployment.yaml`

Hi @Ankurk99 
It will directly deploy in accuknox-agents ns. Even if accuknox-agents ns is not available, it will create one and then deploy

**Comment by yasin-cs-ko-ak** [comment]
@seswarrajan But now we are changed the matchLabels in kubearmor-client for discovery-engine from "container: knoxautopolicy" to "app: discovery-engine". so this won't cause any problems?

**Review by Ankurk99 — APPROVED** [review]

**Pull request merged**
