### PR TITLE
Issue #675: karmor summary flags are ignored

### LINKED ISSUE #675: `karmor summary` flags are ignored
https://github.com/accuknox/discovery-engine/blob/4117eadb3716ec2c88acbbc94a57495f44c63ce5/src/observability/kubearmor.go#L219-L227

Only `req.PodName` is respected, the rest of the parameters in the request are ignored.

```bash
$ karmor summary -p pod-1 --container redis
```
```
local port to be used for port forwarding discovery-engine-746fccb855-nlr6k: 32897 

  Pod Name        pod-1  
  Namespace Name  default                             
  Cluster Name    default                             
  Container Name  nginx                               
  Labels          app=nginx-client-side               
...
```

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Closes #675 

PR for kubearmor-client: https://github.com/kubearmor/kubearmor-client/pull/276

### CODE REVIEW

**Review by seswarrajan — COMMENTED** [review]
@Vyom-Yadav 
This change LGTM. 

Is it possible to modify the protobug request structure to include deployment_name as well, The SQL code already supports the change for that.

**Comment by Vyom-Yadav** [comment]
> Is it possible to modify the protobug request structure to include deployment_name as well, The SQL code already supports the change for that.

Do we want deployment_name in response too?

**Comment by seswarrajan** [comment]
It would be better if we have the deployment name in field as well.

**Comment by Vyom-Yadav** [comment]
We return just the pod_name in response, do we want to return the deployment_name too? Of course, it will be shown only if it's not empty.

**Review by seswarrajan — APPROVED** [review]

**Comment by seswarrajan** [comment]
> We return just the pod_name in response, do we want to return the deployment_name too? Of course, it will be shown only if it's not empty.

We can handle this in a separate PR

**Pull request merged**
